### ISSUE TITLE
C++ Doxygen documentation

### ISSUE THREAD

**Issue by bvadorno** [dqrobotics/cpp#1]
Murilo,

Could you please generate the Doxygen documentation files and make them available as an online HTML page? The idea is to automatically update this documentation HTML page at each _push_. Please see an example [here](https://svn.code.sf.net/p/macroufmg/littlejohn/mobilemanipulator/trunk/ROS/catkin_ws/src/littlejohn_control/src/documentation/html/index.html).

**Comment by mmmarinho** [comment]
Added in 808bd22.

Used an approach a bit different from what you mentioned. The doxygen documentation is built and uploaded by travis to the following page (only pushes to the "release" branch will trigger doxygen the update):
https://dqrobotics.github.io/cpp/index.html

An example page:
https://dqrobotics.github.io/cpp/classDQ__robotics_1_1DQ__Kinematics.html
