### ISSUE TITLE
Implementation of abstract class DQ_Kinematics

### ISSUE THREAD

**Issue by bvadorno** [dqrobotics/cpp#10]
Following the discussion https://github.com/orgs/dqrobotics/teams/developers/discussions/1, we must implement the abstract class `DQ_Kinematics`, change the name of `DQ_kinematics` to `DQ_SerialManipulator` and adapt it according to the new architecture. The implementation in Matlab is currently in branch _mobile_base. I suggest creating a new branch in C++ to implement those functionalities in order to ensure that the _master_ branch remains stable.

Cheers,
Bruno

**Comment by mmmarinho** [comment]
Should be fully functional
