### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by bvadorno** [dqrobotics/cpp#12]
**Context**: Directory structure should be the same across all DQ Robotics languages.

The current Matlab folder structure is given as follows:

Folder name| Description
------------ | -------------
`@DQ`| Contains the DQ class and all the associated methods spread across different files. Since this class is quite complex and have several methods and mathematical operations, in Matlab we need to use the @-type folder to split the methods across different files. 
examples | Contains several examples on how to use DQ Robotics in Matlab. The internal folder structure depends on the language because some examples do not make so much sense in some languages (for instance, plot function usage).
legacy | Legacy classes and methods that will be removed in the next major library improvement. 
robot_control | Classes for robot control. Since the architecture of the `DQ_KinematicController` will be changed in the future, such that we have one abstract superclass and several concrete subclasses, each one implementing a specific controller, it is a good idea to place all of them in a specific folder.
robot_modeling | Classes for robot modeling. Since now we have several robot classes, and not only Serial Manipulators anymore, it is a good idea to place all of them in one separate directory. I used the American spelling for 'modeling'. Currently, the C++ version is written in British spelling. I suggest we stick with just one. 😃 
robots | Robot definitions currently supported by DQ Robotics
utils | Utility functions and classes.
vrep_interface | V-Rep classes

**Suggestion**: Replicate this directory structure in C++.

**Comment by mmmarinho** [comment]
Hello, @bvadorno 

Seems good to me. I'd like to suggest only one change

Folder | Description
------------ | -------------
interfaces | Interface classes, such as V-Rep. In C++, for example, I have a CPLEX interface class which is not in the repo but will eventually be added.

Kind regards,
Murilo
