### ISSUE TITLE
Improve documentation and performance of dqrobotics-cpp

### ISSUE THREAD

**Issue by bvadorno** [dqrobotics/cpp#13]
Hi, @mmmarinho,

I've edited this message in order to reflect https://github.com/dqrobotics/cpp/issues/13#issuecomment-483084301.

General suggestion: for all Jacobians, put the associated bibliographic reference.

List of things to review:
- [x] `line_jacobian`
- [x] `plane_jacobian`

## `line_jacobian`

The comments of `DQ_Kinematics::line_jacobian()` are outdated as they do not reflect the signature established in https://github.com/dqrobotics/matlab/issues/12#issuecomment-478433515.

Furthermore, I suggest changing 
`haminus4(line_direction*conj(xr))*Jr + hamiplus4(xr*line_direction)*C4()*Jr`
to
`(haminus4(line_direction*conj(xr)) + hamiplus4(xr*line_direction)*C4())*Jr`.

The former has three matrix multiplications and 1 matrix addition; the latter has 1 matrix addition and only two matrix multiplications. 🤓 

## `plane_jacobian`

The comments of `DQ_Kinematics::plane_jacobian()` are outdated as they do not reflect the signature established in https://github.com/dqrobotics/matlab/issues/12#issuecomment-478433515.

Analogously to the `line_jacobian`, I also suggest changing 
`Jnz = haminus4(plane_normal*conj(xr))*Jr + hamiplus4(xr*plane_normal)*C4()*Jr` 
to
`Jnz = (haminus4(plane_normal*conj(xr)) + hamiplus4(xr*plane_normal)*C4())*Jr`;

Cheers,
Bruno

**Comment by mmmarinho** [comment]
Hello, @bvadorno,

Compared to MATLAB I think that the C++ documentation is quite lacking in many ways 😭. I think you'll have many other comments so we can concentrate them in this thread. 

Kind regards,
Murilo

**Comment by bvadorno** [comment]
Hi, @mmmarinho,

No problem. We'll have to figure out how to make unified documentation for all of them. Although [readthedocs.org](readthedocs.org) is great from the user's point-of-view, good comments in the code are paramount from the developer's point-of-view. I was wondering if we could automate this process somehow.

By the way, have you seen the **brand new** Matlab's `@DQ` documentation? I think we've reached a whole new level. 🤓 😍 

Cheers,
Bruno
