### ISSUE TITLE
Implementation of utility functions

### ISSUE THREAD

**Issue by bvadorno** [dqrobotics/cpp#14]
**Context**: There are several utility functions that might be useful in the current development as they increase code readability, brevity, and interoperability between DQ objects and standard types.

For instance, suppose that we have a DQ object `dq` such that `dq = 1.5`. If a given function accepts `double` parameters, instead of doing `dq.q(1)` in Matlab (or `dq.q(0) `in C++), it is more appropriate to cast that object to double (i.e.,`double(dq)`). In addition to providing a cleaner code, we end up with an exact code for both Matlab and C++ without having to worry about indexes, which are different across different languages. ([This link](https://www.learncpp.com/cpp-tutorial/910-overloading-typecasts/) shows how to overload typecasts in C++).

For sure, such a cast only makes sense (at least from a semantic point of view), if the DQ object`dq` corresponds to a 'strict' real number; that is, a real number with imaginary part equal to zero and dual part equal to zero too. Therefore, in order to increase readability we should also implement functions to verify if a dual quaternion is real, pure, a quaternion, etc.

**Suggestion**:

- [x] implement the casting of a dual-quaternion real-number to `double` 
- [x] implement `is_pure` (1 if real part is 0 and 0 otherwise)
- [x] implement `is_real` (1 if imaginary part is 0 and 1 otherwise)
- [x] implement `is_real_number` (1 if imaginary and dual parts are 0 and 0 otherwise)
- [x] implement `is_quaternion` (1 if dual part is 0 and 0 otherwise)
- [x] implement `is_pure_quaternion` (1 if `is_pure` and `is_quaternion`, 0 otherwise)
- [x] implement `is_line` (1 if `is_pure` and `is_unit`, 0 otherwise)
- [x] implement `is_plane` (1 if `is_unit` and `is_real(D(x))`)

**Comment by mmmarinho** [comment]
Hello, @bvadorno,

Thanks for the suggestions. 

C casts are not appropriate for C++ and give a warning in modern compilers: "Warning: using old-style cast".
I'll implement an [explicit type conversion](https://en.cppreference.com/w/cpp/language/explicit_cast) instead.

**Comment by bvadorno** [comment]
Hi, @mmmarinho.

Yes, indeed I was referring to modern-style cast, such as the functional cast (i.e., double(x)), which is the one that we're using in Matlab.

Cheers,
Bruno
