### ISSUE TITLE
distance_jacobians and residuals

### ISSUE THREAD

**Issue by bvadorno** [dqrobotics/cpp#15]
**Context**: Signature parameters are unnecessarily verbose, the implementation is not "language-proof", and utility functions should be used to obtain a cleaner code.

**Suggestions**: 

- [x] Change  variables such as `robot_point_translation` to `robot_point`. 
- [x] Instead of using `return dq.q(0)`, use the casting to double proposed in #14 to obtain a "language-proof" solution. 
- [x] Use the utility functions to verify if, for instance, a given dual quaternion is just a pure quaternion (`is_pure_quaternion(dq)`).
- [x] Verify if all geometric primitives passed as parameters fulfill their respective requirements. For instance, a point must be a pure quaternion whereas a plane must have unit norm and the imaginary component of its dual part must be zero, etc.
- [x] In `point_to_plane_distance_jacobian`, it is not necessary to compute `const DQ d = D(workspace_plane)`;
- [x] `plane_to_point_distance_jacobian` does not need the `robot_plane` argument. Furthermore, ` DQ n_pi = P(robot_plane)` and `DQ d_pi = D(robot_plane)` can be removed;
- [x] Fix the bugs listed below.

**Specific Points** (I may edit the issue in the very near future to accommodate other bugs, in case I encounter more of them): 

1. I think that point_to_point_residual is returning the wrong value (it should be `q(0)` instead of `q(1)`, right?). The casting to double will prevent those kinds of minor-but-very-annoying mistakes.
2. `line_to_line_distance_jacobian` currently only implements the Jacobian for the case where the lines are not parallel.
3. `line_to_line_residual` currently only implements the residual for the case where the lines are not parallel.

**Comment by mmmarinho** [comment]
Hello, @bvadorno ,

I fixed the bugs so far so I'll close it and you can re-open when something else comes up. I'm sure something will.
