### ISSUE TITLE
Improvements on DQ_Geometry

### ISSUE THREAD

**Issue by bvadorno** [dqrobotics/cpp#16]
Hi, @mmmarinho 

I suggest some changes in the file `DQ_Geometry`.

1.  Following the same reasoning that we used when designing [`DQ_Kinematics`](https://github.com/orgs/dqrobotics/teams/developers/discussions/1), I think it's better to make `DQ_Geometry` a class with static methods instead of just a file with functions inside the namespace `DQ_Robotics`. The reasons for doing so are threefold: first, Matlab does not have the same namespace mechanism as C++; second, we maintain consistency (in terms of our adopted development conventions) inside the overall library; third, we know exactly where those functions are coming from, which helps in the maintainability.

2. For all squared distances, instead of doing something like `pow((vec4(cross(point,l)-m).norm()),2);`, it is more efficient writing something like  
```
new_point = cross(point,l)-m;
vec4(new_point)'*vec4(new_point);
```

**Comment by mmmarinho** [comment]
Hello, @bvadorno 

Just FYI, I followed your suggestion and just changed a little bit since we were focusing efficiency
```
const Vector4d a = vec4(cross(point,l)-m);
return a.transpose()*a;
```

**Comment by bvadorno** [comment]
Great! Indeed, just one `vec4` mapping instead of two.

#EfficiencyWithoutSacrificingCodeReadability
