### ISSUE TITLE
[QUESTION] Compilation issues 

### ISSUE THREAD

**Issue by tgn3000** [dqrobotics/cpp#19]
Hi, Dear Dev!

When I did
```
git clone https://github.com/dqrobotics/cpp.git dqrobotics
cd dqrobotics
mkdir build
cd build
cmake ..
make
```
CMake does not pick up the include path of my Eigen3. I have to modify 
```
build/CMakeFiles/dqrobotics.dir/flags.make
```
to make it work, replacing
```
dqrobotics/EIGEN3_INCLUDE_DIR
```
with my Eigen3 path. Here's what CMake gave me
```
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/lib/ccache/cc
-- Check for working C compiler: /usr/lib/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/ccache/c++
-- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mujin/Repos/dqrobotics/build
```
so it seems to me your CMakeLists.txt does not pick up the Eigen3's directory.

Also it appears that the unit test is no longer working, as you seem to have removed/moved some "legacy" controller files. I would like to get the unit test working again, so that I could learn the usage of your double quaternion functions. Thank you!

**Comment by mmmarinho** [comment]
Hello, @tgn3000 

Regarding your compilation issues, could you give me more information about your system
- Are you on Ubuntu, what version?
- How did you install eigen3?

Just FYI, if you are running Ubuntu, the best way to install the library is through the PPA, so what you don't need to compile from source. The development PPA, with the latest code, is available at:
```
sudo add-apt-repository ppa:dqrobotics-dev/development
sudo apt-get update
sudo apt-get install libdqrobotics
```

As for the second part of your question, we are working on having the unit tests working in a future version of the library. For now, you can take a look at the examples repository to get the hang of it
https://github.com/dqrobotics/cpp-examples

Lastly, we're working to make all supported languages of the library quite close to each other, so you might also get some useful info from the MATLAB examples
https://github.com/dqrobotics/matlab/tree/master/examples

Kind regards,
Murilo

**Comment by mmmarinho** [comment]
More information is needed.
