### ISSUE TITLE
Implementation of raw_jacobian

### ISSUE THREAD

**Issue by bvadorno** [dqrobotics/cpp#2]
Hi, Murilo

I've just implemented the function `raw_jacobian` on Matlab and adapted the Jacobian function accordingly. The `raw_jacobian` calculates the Jacobian matrix without taking into consideration any constant base and end-effector displacements. In addition, following Juancho's request (Ticket 27 on SourceForge), now we have the option to use `robot.jacobian(q, ith)`, which calculates the Jacobian up to the _i-th_ link. Could you please implement those functionalities in C++?

Cheers,
Bruno

**Comment by mmmarinho** [comment]
Hello, Bruno,

Will do.
The "bug" label confused me a bit. Besides the additions, is there some bug I should look out for?

Kind regards,
Murilo

**Comment by bvadorno** [comment]
Hi, Murilo.

There is no bug. It's more like a feature request, although I feel that missing functions will eventually lead to a bug. To avoid confusion, I'll change the label.

Cheers,
Bruno
