### ISSUE TITLE
[QUESTION] Is there a way to change the robot of a DQ_SerialManipulator during runtime?

### ISSUE THREAD

**Issue by marcos-pereira** [dqrobotics/cpp#27]
Hello, 

I would like to know if there is a way to change the robot of a DQ_SerialManipulator during runtime.

Something like:

```
DQ_SerialManipulator robot_serial_manipulator();
...
robot_serial_manipulator = KukaLw4Robot::kinematics();
...
robot_serial_manipulator = AnotherRobot::kinematics();
...
robot_serial_manipulator = MyOtherRobot::kinematics();
...
```
This yields an error of the following type
```
error: cannot convert ‘DQ_robotics::DQ_SerialManipulator’ to ‘DQ_robotics::DQ_SerialManipulator()’ in assignment
```

My goal is to be able to use the robot_serial_manipulator overall in the code without having to declare a DQ_SerialManipulator for each robot. I want to use the same code for different robots chosen during runtime.

Stable PPA
DQ Robotics version: 19.10.0-0~201910030916~ubuntu18.04.1

Thank you,

Marcos

**Comment by mmmarinho** [comment]
Hello, @marcos-pereira,

Yes!
Calling the constructor `DQ_SerialManipulator()` is [deleted](https://github.com/dqrobotics/cpp/blob/8e0ca2a0f5f2dfa857612b9ef8660f05aea35bba/include/dqrobotics/robot_modeling/DQ_SerialManipulator.h#L46) because an uninitialized `DQ_SerialManipulator` doesn't make sense and calling any of its methods would have unspecified behavior.

The correct way to do this is with a pointer. From what I understand of your problem, a raw pointer would suffice:
```cpp
#include <iostream>
#include <vector>

#include <dqrobotics/robot_modeling/DQ_SerialManipulator.h>
#include <dqrobotics/robots/KukaLw4Robot.h>
#include <dqrobotics/robots/Ax18ManipulatorRobot.h>
#include <dqrobotics/robots/ComauSmartSixRobot.h>

using namespace DQ_robotics;

void do_something_with_dq_serial_manipulator(DQ_SerialManipulator* robot)
{
    std::cout << "Joint count: " << robot->get_dim_configuration_space() << std::endl;
}

void test_issue_27()
{
    DQ_SerialManipulator robot_a = KukaLw4Robot::kinematics();
    DQ_SerialManipulator robot_b = Ax18ManipulatorRobot::kinematics();
    DQ_SerialManipulator robot_c = ComauSmartSixRobot::kinematics();

    std::vector<DQ_SerialManipulator*> serial_manipulators;
    serial_manipulators.push_back(&robot_a);
    serial_manipulators.push_back(&robot_b);
    serial_manipulators.push_back(&robot_c);

    for(DQ_SerialManipulator* serial_manipulator: serial_manipulators)
    {
        do_something_with_dq_serial_manipulator(serial_manipulator);
    }
}

int main(void)
{
    test_issue_27();
    return 0;
}
```
