### ISSUE TITLE
Implementation of jacobian_dot and the corresponding example

### ISSUE THREAD

**Issue by bvadorno** [dqrobotics/cpp#3]
Hi Murilo,

I've just implemented the function `jacobian_dot` to calculate the time derivative of the Jacobian matrix in Matlab (Ticket 30 of Sourceforge). I also implemented an example (_jacobian_time_derivative.m_) to compare the analytical expression with a numerical one. Could you please implement the `jacobian_dot` method, which in the Matlab version is inside `@DQ_kinematics`, and also a simple example like the one I mentioned?

Thanks,
Bruno

**Comment by bvadorno** [comment]
Hi, @mmmarinho 

I was wondering if a better name would be jacobian_derivative instead of jacobian_dot. What do you think?

Cheers,
Bruno

**Comment by mmmarinho** [comment]
Hello, @bvadorno 

I prefer that name. In c++ we have been using camelcase for the jacobian functions (jacobianDerivative), but we can change to the underline.

**Comment by bvadorno** [comment]
I think we should continue using the C++ Google Style. However, in that style functions start with an uppercase.

Bruno
