### ISSUE TITLE
[BUG] Rename of is_stable_ and is_stable() 

### ISSUE THREAD

**Issue by bvadorno** [dqrobotics/cpp#31]
Hi, @mmmarinho,

The variable `is_stable_` and the method `is_stable()` in `DQ_KinematicController` are not appropriate as 'stability' is an expression in control theory with a very precise meaning. To reflect in C++ the renaming of those variable and method that I did in Matlab, could you please change them to `system_reached_stable_region_` and `system_reached_stable_region()`, respectively?

Cheers,
Bruno

**Comment by mmmarinho** [comment]
Hello, @bvadorno,

Done!
