### ISSUE TITLE
Implement the sharp conjugation operation

### ISSUE THREAD

**Issue by bvadorno** [dqrobotics/cpp#4]
Murilo, I've just implemented the sharp conjugation operation in Matlab (matlab/@DQ/transpose.m). Could you please add it to the C++ code? 

See Eq. (2.5.3) from Adorno, B. V. (2017). Robot Kinematic Modeling and Control Based on Dual Quaternion Algebra -- Part I: Fundamentals, which can be found [here](https://hal.archives-ouvertes.fr/hal-01478225v1.)

**Comment by mmmarinho** [comment]
You mean the one in Eq. (2.5.4) page 34?

C++ doesn't have the ' operator. A similar one would be to use transpose() as they use in eigen3.

In this version I called it sharp() since it's not actually a transposition. Or is it?

**Comment by bvadorno** [comment]
Hi, Murilo.

Yes, this one. Indeed, it is not a transpose. Instead, it is a type of conjugate, as the name suggests. Therefore, `sharp` is a good name.

Cheers,
Bruno
