### ISSUE TITLE
[BUG] Small typo in ([DQ_QuadraticProgrammingController.cpp](line 70)

### ISSUE THREAD

**Issue by juanjqo** [dqrobotics/cpp#46]
Hi @mmmarinho, I spotted a small typo. I'm certain that I will forget about it if I don't write about it here. 

**Bug description**
- There is a small typo in DQ_QuadraticProgrammingController.cpp (line 70).  It is written "feedoforward" instead of "feedforward".
Current:
`throw std::runtime_error("Incompatible sizes between task error and feedoforward in compute_tracking_control_signal");`

- Instead of:
`throw std::runtime_error("Incompatible sizes between task error and feedforward in compute_tracking_control_signal");`
 

*Code*

```
 DQ_QuadraticProgrammingController.cpp
```

**Environment:**
 - dqrobotics version: C++ (master branch)

**Comment by mmmarinho** [comment]
@juanjqo Great catch, thanks!
