### ISSUE TITLE
Cooperative framework is missing in C++.

### ISSUE THREAD

**Issue by juanjqo** [dqrobotics/cpp#5]
Hi Murilo, 

I realized that the cooperative dual space framework is implemented on Matlab (@DQ_cdts) but is not available for C++.  It is possible add this functionality in the C++ version?

Cheers,

Juancho.

**Comment by mmmarinho** [comment]
Hello, Juan,

Thank you for the suggestion. 

Recently, @bvadorno and I are defining the naming conventions for the whole library. Maybe the function names in DQ_cdts will change. 

After that is decided I can add the functionality of DQ_cdts to the C++ library quite fast.

Kind regards,
Murilo

**Comment by juanjqo** [comment]
Great!
Thanks.
Furthermore, all C++ updates will be automatically available for Python isn't? (I'm migrating all my codes to Python).

Cheers,

Juancho

**Comment by bvadorno** [comment]
Hi, Juancho. 

> Furthermore, all C++ updates will be automatically available for Python isn't? (I'm migrating all my codes to Python).

Not necessarily, because it depends on the bindings. If new ones are needed, you should expect a delay. Otherwise, if only the internal mechanisms of a given C++ function change, then it should be automatically, right @mmmarinho ?

Cheers,
Bruno

**Comment by mmmarinho** [comment]
Added as DQ_CooperativeDualTaskSpace in cpp.

> Not necessarily, because it depends on the bindings. If new ones are needed, you should expect a delay. Otherwise, if only the internal mechanisms of a given C++ function change, then it should be automatically, right @mmmarinho ?

This is pretty much it.

Uploading changes to pip is also a manual process for now so it takes a while.

Kind regards,
Murilo

**Comment by mmmarinho** [comment]
@juanjqo  I also updated the python version just now. If there's something wrong with it you can open an issue for the Python library.

**Comment by juanjqo** [comment]
@mmmarinho Thanks!  :D
