### ISSUE TITLE
[BUG] lack of pure virtual method overload in DQ_SerialManipulatorDense

### ISSUE THREAD

**Issue by chewheel** [dqrobotics/cpp#50]
**************************
### Acceptance of the Code of Conduct
_Leave these in your bug report, read, and check them._ 
- [ ] I understand that support for DQRobotics is given voluntarily. 
- [ ] In understand that any possible response and its timeliness will be based on the relevance, accuracy, and politeness of my request and the following discussion.
- [ ] If a DQRobotics member replies, I will let them know, politely, if their response solves my issue or not. 
*************************

**Bug description**
- lack of overload of virtual Eigen::MatrixXd DQ_robotics::DQ_SerialManipulator::raw_pose_jacobian_derivative(const VectorXd&, const VectorXd&, const int&) const  in DQ_SerialManipulatorDenso

**To Reproduce**
- Please add the code you ran and the output you had, including error messages.
- In case of C++, add the `#include` part of your code as well
- In case of Python, add the `import` part of your code as well
- Format it using code tags:

*Code*

```
code here
```
*Output*
```
output here
```

**Expected behavior**
- A clear and concise description of what you expected to happen.

*Expected output*
```
expected output here
```

**Environment:**
 - OS: [e.g. Ubuntu 16.04, Ubuntu 18.04]
 - dqrobotics version
 - Python version [e.g. 3.6, 3.7 (If applicable)]
 - MATLAB version [e.g., 2018b, 2019a, (if applicable)]

**Additional context**
- Add any other context about the problem here.

**Comment by mmmarinho** [comment]
Should be fixed by #51.
