### ISSUE TITLE
[LANGUAGE INCOMPATIBILITY] The matrices Q4 and Q8 are not implemented

### ISSUE THREAD

**Issue by marcos-pereira** [dqrobotics/cpp#55]
**************************
### Acceptance of the Code of Conduct
_Leave these in your bug report, read, and check them._ 
- [x] I understand that support for DQRobotics is given voluntarily. 
- [x] In understand that any possible response and its timeliness will be based on the relevance, accuracy, and politeness of my request and the following discussion.
- [x] If a DQRobotics member replies, I will let them know, politely, if their response solves my issue or not. 
*************************

Hello guys,

**Describe the missing/unexpected functionality**
The matrices Q4 and Q8 are not implemented in the [DQ class](https://github.com/dqrobotics/cpp/blob/master/src/DQ.cpp) as they are implemented in the MATLAB version of the [DQ class for Matlab](https://github.com/dqrobotics/matlab/blob/d0eabe37a21ff86c4cceb6ff1747afcf89c7d4a7/%40DQ/Q8.m).

Would it be possible for you to implement them? Or should I implement them and do a pull request?

**Environment:**
 - OS: Ubuntu 22.04
 - dqrobotics version 20.04.0-0~202005090156~ubuntu22.04.1

Kind regards,
Marcos Pereira

**Comment by mmmarinho** [comment]
@juanjqo Could you try to work on this one with @marcos-pereira?

A quick reminder in case the steps aren't clear:
1. Update `DQ_test.m` and `DQ_test.mat` in https://github.com/dqrobotics/python-tests.
2. Update `DQ.cpp` and `DQ.h` (with the proper credit attribution) in https://github.com/dqrobotics/cpp.
3. Update `DQ_py.cpp` https://github.com/dqrobotics/python.

Such that all tests run properly.

**Comment by juanjqo** [comment]
@mmmarinho sure!

**Comment by marcos-pereira** [comment]
Hello @mmmarinho and @juanjqo ,

Thank you for the quick response. I have forked the repository and I am implementing the Q4 and Q8 matrices. After I finish it, I will try the pull request.

Best regards,
Marcos

**Comment by mmmarinho** [comment]
@marcos-pereira @juanjqo 

it seems that Q4 isn’t exposed in MATLAB?
https://github.com/dqrobotics/python-tests/pull/6

To add it to CPP we need to first have it working as intended in MATLAB, otherwise we’ll trade one language incompatibility for another. 

Can you two figure out what’s up? If this is the intended behavior then we can also make Q4 inaccessible in CPP, although in my superficial understanding of things this does not seem to make much sense.

**Comment by marcos-pereira** [comment]
@mmmarinho @juanjqo 

just let me know if you need more help to solve this issue and complete PR #56 . I saw that @juanjqo is already working on that in the MATLAB repository.

**Comment by mmmarinho** [comment]
Added in #56
