### ISSUE TITLE
[QUESTION] Is there a way to get the ith link x of a DQ_SerialManipulatorDH during runtime? 

### ISSUE THREAD

**Issue by st-suzuki-sec** [dqrobotics/cpp#63]
Hello,

I would like to know if there is a way to get the ith link x(pose) of a DQ_SerialManipulatorDH during runtime.
（In the case of 7th link manipulator, I would like to get 2th link x or 5th link x.）

I know to get top pose from fkm.

Thank you

**Comment by juanjqo** [comment]
Hi @st-suzuki-sec, 

I am not sure if I understood your question. Let's say you want to compute intermediate poses in the DQ_SerialManipulator subclasses. In that case, you can use the signature `fkm(q, ith)`, where `ith` denotes the ith-link to be computed.

![image](https://github.com/dqrobotics/cpp/assets/23158313/482a0b62-2065-4133-a9e3-91e2d7056ac1)


Documentation taken from [here](https://github.com/juanjqo/matlab/blob/master/robot_modeling/DQ_SerialManipulator.m)
```cpp
/*   FKM(q, ith) calculates the FKM up to the ith link.
      If ith is the last link, it DOES NOT take into account the
      trasformation given by set_effector. If you want to take
      into account that transformation, use FKM(q)
      instead. */

DQ x1 = fkm(q,0);  // Pose of the first link.   
DQ x2 = fkm(q,1); // Pose of the second link.
DQ xn = fkm(q);   // Pose of the last link, taking into account the end-effector

```

### Minimal Example

```cpp
#include <iostream>
#include <dqrobotics/robots/Ax18ManipulatorRobot.h>

using namespace DQ_robotics;
using namespace Eigen;

int main()
{
   auto robot = Ax18ManipulatorRobot::kinematics();
   auto q = VectorXd::Zero(robot.get_dim_configuration_space());

   for(auto i=0; i< robot.get_dim_configuration_space();i++)
   {
       auto x = robot.fkm(q,i);
       std::cout<<" Pose of the joint "<<i+1<<":  "<<x<<std::endl;
   }
}

```

Please let me know if you can solve your issue.



Best regards, 


Juan

**Comment by st-suzuki-sec** [comment]
Thanks so match!
I solved the my problem!
(I missed that description...)
