### ISSUE TITLE
[QUESTION] Is there a way to get the finite line from Plucker line?

### ISSUE THREAD

**Issue by st-suzuki-sec** [dqrobotics/cpp#64]
Hello,

I would like to know if there is a way to get the finite line from Plucker line.
I image not to collide like between just only real shaft part (line) and other real shaft part (line).

```cpp
double DQ_Geometry::line_to_line_squared_distance(const DQ& line1, const DQ& line2)
```
https://github.com/dqrobotics/cpp/blob/77acf9a42875ffb69e9f48f98f3950f9d7242c0e/src/utils/DQ_Geometry.cpp#L118C21-L118C50

![image](https://github.com/dqrobotics/cpp/assets/109952932/8b40e691-74f9-4ad3-b9b0-3e3a761a9e9b)

Thank you !

**Comment by mmmarinho** [comment]
Hi @st-suzuki-sec,

I think what you mean/want is a line segment. You can use the following methods to do so.

https://github.com/dqrobotics/cpp/blob/77acf9a42875ffb69e9f48f98f3950f9d7242c0e/src/utils/DQ_Geometry.cpp#L378-L383

https://github.com/dqrobotics/cpp/blob/77acf9a42875ffb69e9f48f98f3950f9d7242c0e/src/robot_modeling/DQ_Kinematics.cpp#L824-L832

I implemented these as a generalisation of http://doi.org/10.1109/TRO.2019.2920078 and it is used extensively in http://doi.org/10.1109/MRA.2023.3336472.

**Comment by st-suzuki-sec** [comment]
I'm sorry late to reply,,,

Thanks so match!
I solved the my problem!

I appreciate for the quick reply!

**Comment by st-suzuki-sec** [comment]
Hi @mmmarinho 
I'm sorry. I want to reopen this issue.

Beacuse I cloudn't solve my problem. I tried to use below method you told me.
https://github.com/dqrobotics/cpp/issues/64#issuecomment-1983307061

But error occured like this.
```
error: ‘class DQ_robotics::DQ_SerialManipulatorDH’ has no member named ‘line_segment_to_line_segment_distance_jacobian’
error: ‘line_segment_to_line_segment_squared_distance’ is not a member of ‘DQ_robotics::DQ_Geometry’
```

I used libdqrobotics that version is [20.04.0-0~202005090156~ubuntu20.04.1].
Do I need to download raw source code and build ?

Thank you !

**Comment by mmmarinho** [comment]
Hi @st-suzuki-sec,

No worries, please keep engaging until we've reached a conclusion.

I think you have the `release` PPA installed but,  to use the novelties I described, you'll need the `development` PPA version.

Could you let me know if the procedure below fixes your issue? Please understand that the development PPA does come with its own set of warnings and possible changes in the API between versions.
https://dqroboticsgithubio.readthedocs.io/en/latest/installation/cpp.html#development-ppa

**Comment by st-suzuki-sec** [comment]
Hi @mmmarinho

Thank you for replay!
Yes, I installed `release` PPA version.
I try above `development` PPA version!

If I confuse, I possibly ask you question,,,
anyway, I assumed the problem is resolved!
