### ISSUE TITLE
Geometric primitives Jacobians for C++

### ISSUE THREAD

**Issue by juanjqo** [dqrobotics/cpp#7]
Hi @mmmarinho  and @bvadorno !

There are plans (in the very near future) to include the geometric primitives Jacobians (line-line, point-line, plane-point...etc, as described in the paper [Active Constraints Using Vector Field Inequalities for Surgical Robots](https://ieeexplore.ieee.org/abstract/document/8461105) in the DQ Robotics (For Matlab, C++ and Python)? 
I have my personal implementation on Matlab but I want to use the Python version. 

Best regards!

Juancho

**Comment by bvadorno** [comment]
Hi, Juancho. 

Our plans are even better. \o/ 

We plan to implement the geometric primitives of this paper: [Dynamic Active Constraints for Surgical Robots using Vector Field Inequalities](https://arxiv.org/abs/1804.11270), which generalize the ones in the paper you mentioned. You should expect them in a couple of weeks, though.

Cheers,
Bruno

**Comment by juanjqo** [comment]
That is great news!  :D
Cheers,
Juancho

**Comment by mmmarinho** [comment]
I added some of the functions that we will need to implement the geometric primitive Jacobians in C++, Python will lag behind a bit.

Adding too many things at once makes the translation into MATLAB & Python difficult so I'll wait until we discussed and fixed
dqrobotics/matlab#11 and dqrobotics/matlab#12
before moving forward.

**Comment by juanjqo** [comment]
Ok, I get it.
😃
I'll wait.

**Comment by mmmarinho** [comment]
Hello, @juanjqo @bvadorno 

I added the geometric primitive Jacobians to C++ and Python.

I also added the Python 3.6 and 3.5 compilation to the continuous integration. This means that every time something is pushed to the repository it will update in PyPi within a few minutes.

I'll close this issue for and please open another issue if something odd happens.

Kind regards,
Murilo

**Comment by juanjqo** [comment]
Great !!!
Thanks!.
