### ISSUE TITLE
Robot naming

### ISSUE THREAD

**Issue by bvadorno** [dqrobotics/cpp#8]
**Context**: Naming convention should follow the Google Python Style Guide, but currently  in both C++ and Matlab, functions for creating robots are not following the convention.

For instance, in C++, a KUKA robot is currently declared as `DQ_kinematics kuka = KukaKinematics()`
and in Matlab it is declared as `kuka = DQ_KUKA`.

**Suggestion**: Use the following convention for functions used to create new robots:
`new_robotname_robot`

Therefore, a Kuka robot in C++ would be declared as `DQ_kinematics kuka = new_kuka_robot()` and in Matlab as  `kuka = new_kuka_robot`.

Cheers,
Bruno

**Comment by mmmarinho** [comment]
Hello, Bruno,

To make the robot classes a bit more future-proof, how about we do something like

```
class YourFavoriteRobot
{
  static DQ_kinematics kinematics(...)
};
```

So that in the future we could add
```
DQ_dynamics dynamics(...);
VectorXd upper_joint_limits();
```

and so on?

**Comment by bvadorno** [comment]
Hi, Murilo,

Yes, it is a good idea. I suggest we always use the following convention for robot class names: `FullNameRobot`. For instance, `KukaLwr4Robot`, `ComauSmartSixRobot`, etc.

We should also use the same directory naming convention. Currently, we use in Matlab the name `DQ_robots` and in C++ we use the name `robot_dh`. First, we need to establish a common name, and then we need to define which convention we'll use for file naming. Both C++ and Python use `lower_case_with_underline` convention for file names, therefore we can use the same reasoning for directory names (except for classes in Matlab, which require a file name that is equal to the class name). 

Furthermore, `robot_dh` is not an ideal name, since a robot is independent of the parametrization. Therefore, I suggest something like `robot_classes`. What do you think?

Cheers,
Bruno

**Comment by mmmarinho** [comment]
Hello, Bruno,

The robot class naming convention you suggested, `FullNameRobot`, seems reasonable to me.

I also agree that the current `robot_dh` folder is not ideal. 
It is a very minor thing but how about we call the folder just `robots` so that when included in the code it will read as
```#include <dqrobotics/robots/FullNameRobot.h> ```

which looks a little better than
```#include <dqrobotics/robot_classes/FullNameRobot.h>```
since the `classes` part can maybe be inferred since we are using object-oriented programming.

Kind regards,
Murilo

**Comment by bvadorno** [comment]
Hi, Murilo.

No problem. Let's settle with `robots`. By the way, have you seen the new team I started in order to discuss topics that go beyond a specific DQ Robotics programming language?

Cheers,
Bruno

**Comment by mmmarinho** [comment]
Hello, Bruno,

I saw it, thanks!
