### ISSUE TITLE
Implementation of set_reference_frame() and set_base_frame()

### ISSUE THREAD

**Issue by bvadorno** [dqrobotics/cpp#9]
**Context**: In the class `DQ_kinematics`, the method `set_base` is always given with respect to the identity frame (i.e., the global reference one). This has been used to define the physical location of the robot with respect to the global reference frame (in Matlab, for instance, `set_base` is extensively used in the function `plot()`, but the issue I'll describe below is independent of the programming language). This is particularly important when we have several robots in the workspace and we want to determine their physical location with respect to a common frame, but we want to perform motion control on a local frame (for example, each robot uses the frame located at its base as the reference frame). 

Therefore, sometimes it is useful to use a reference frame that does not coincide with the base frame, which means that the robot is physically located in one place, but the reference frame can be another one (e.g., for example, a camera reference frame). This is particularly important in serially coupled kinematic chains (i.e., complete kinematic chains coupled together to form a larger one) because a particular kinematic chain's end-effector pose is given with respect to the previous kinematic chain's end-effector, not with respect to the global reference frame.

**Proposed solution**: Use two distinct variables, namely `base_frame` and `reference_frame`, where the former is used to physically determine the robot in the workspace and the latter is the reference frame used to determine the end-effector pose. Furthermore, we need to implement the methods 

1.  `set_reference_frame(reference_frame)`;
2.  `set_base_frame(base_frame)`.

Since both `fkm()` and `pose_jacobian()` methods use the transformation given by `base_frame`, they should be adapted accordingly to use `reference_frame` instead.

**Side-effects**: Small, but we need to implement the deprecated function  `set_base`, which must refer to `set_reference_frame`.

I already implemented all those changes in the _mobile_base_ branch. I intend to merge them with the master branch after we decide on the naming conventions related to this issue and issue #8.

Cheers,
Bruno

**Comment by mmmarinho** [comment]
Fixed
